### ISSUE TITLE
収集データがどのような項目を示すのかわからない

### ISSUE THREAD

**Issue by Ningensei848** [4mami/google-scholar-scraper#2]
> Google Scholarの検索結果をCSVファイルに保存するためのツールです

細かくどのような項目が保存できるのか、READMEに説明がない

`page_number,position,title,url,year,publication_info,snippet,pdf_url,cited_num,cites_id,cites_url,version_num,versions_url,result_id`

↑が細目だということ、その細目が何を表しているのかのちょっとした説明くらいはほしい

**Comment by 4mami** [comment]
それはそうなので、readme更新しておきます
初歩的な質問かもだけど、issueのcloseってreadmeを更新し終わったら俺がやっちゃって大丈夫なものなの？　それともopenした人が解決されたと思ったらcloseするもの？

**Comment by Ningensei848** [comment]
会話というか、やり取りが終了したと思われるタイミングで閉じればいいし、その判断は一般的には会話の参加者すべてにある

どちらかが「ボールを投げ」ているのにいきなり close したら心証悪いけど、それでもいいと判断しバシッと閉じる場合もある

時折デカイOSSの issue だと初心者のクソ質問が多数重複して検索を考えるとカスなパターンとかは、"see #2 , right now." みたいなシャットアウトもあったりする、そこはそういう権力構造だね〜と受け入れるしかないかなぁ

---

で、この会話をこれ以上続けると話題がズレまくるので、こちらから閉じておきます（と、こういう感じで一言入れるといいかもと思うのは日本人的な感性かしら…）
